# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 974bb4de56a6f5da690a64709a864a7d554b7c14
    hooks:
    # -   id: check-ast
    # -   id: check-builtin-literals
    # -   id: check-byte-order-marker
    # -   id: check-case-conflict
    # -   id: check-docstring-first
    # -   id: check-executables-have-shebangs
    # -   id: check-json
    # -   id: check-merge-conflict
    # -   id: check-shebang-scripts-are-executable
    # -   id: check-symlinks
    # -   id: check-toml
    # -   id: check-vcs-permalinks
    # -   id: check-xml
    # -   id: destroyed-symlinks
    # -   id: detect-aws-credentials
    # -   id: detect-private-key
    # -   id: double-quote-string-fixer
    # -   id: file-contents-sorter
    # -   id: fix-byte-order-marker
    # -   id: fix-encoding-pragma
    # -   id: forbid-new-submodules
    # -   id: mixed-line-ending
    # -   id: name-tests-test
    # -   id: no-commit-to-branch
    # -   id: pretty-format-json
    # -   id: requirements-txt-fixer
    # -   id: sort-simple-yaml
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
-   repo: local
    hooks:
    -   id: cljfmt-reformat
        name: Reformatting files with cljfmt
        entry: bash -c 'clj -Sdeps "{:deps {cljfmt/cljfmt {:mvn/version \"0.8.0\"}}}" -M -m cljfmt.main fix --indents util/indents.clj'
        stages: [push]
        require_serial: true
        language: system

    -   id: jira-ticket-number-commit-msg
        name: Appending jira ticket number to commit message
        entry: bash -c 'bb --classpath util --main prepare_commit_msg'
        language: system
